## Import Library

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')
plt.style.use('fivethirtyeight')
pd.set_option('display.max_columns', None)

### Import Data (DataFrame CSV, JSON, XLS)

In [2]:
df = pd.read_csv(r'C:\Users\LENOVO\Documents\jupyter\visualisasi\dataset\Automobile_data.csv')
df.head(10)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,width,height,curb-weight,engine-type,num-of-cylinders,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,65.5,52.4,2823,ohcv,six,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,176.6,66.2,54.3,2337,ohc,four,109,mpfi,3.19,3.4,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,176.6,66.4,54.3,2824,ohc,five,136,mpfi,3.19,3.4,8.0,115,5500,18,22,17450
5,2,?,audi,gas,std,two,sedan,fwd,front,99.8,177.3,66.3,53.1,2507,ohc,five,136,mpfi,3.19,3.4,8.5,110,5500,19,25,15250
6,1,158,audi,gas,std,four,sedan,fwd,front,105.8,192.7,71.4,55.7,2844,ohc,five,136,mpfi,3.19,3.4,8.5,110,5500,19,25,17710
7,1,?,audi,gas,std,four,wagon,fwd,front,105.8,192.7,71.4,55.7,2954,ohc,five,136,mpfi,3.19,3.4,8.5,110,5500,19,25,18920
8,1,158,audi,gas,turbo,four,sedan,fwd,front,105.8,192.7,71.4,55.9,3086,ohc,five,131,mpfi,3.13,3.4,8.3,140,5500,17,20,23875
9,0,?,audi,gas,turbo,two,hatchback,4wd,front,99.5,178.2,67.9,52.0,3053,ohc,five,131,mpfi,3.13,3.4,7.0,160,5500,16,22,?

In [7]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symboling          205 non-null    int64
 1   normalized-losses  205 non-null    object
 2   make               205 non-null    object
 3   fuel-type          205 non-null    object
 4   aspiration         205 non-null    object
 5   num-of-doors       205 non-null    object
 6   body-style         205 non-null    object
 7   drive-wheels       205 non-null    object
 8   engine-location    205 non-null    object
 9   wheel-base         205 non-null    float64
 10  length             205 non-null    float64
 11  width              205 non-null    float64
 12  height             205 non-null    float64
 13  curb-weight        205 non-null    int64
 14  engine-type        205 non-null    object
 15  num-of-cylinders   205 non-null    object
 16  engine-size        205 non-null    int64
 17  fuel-system        205 non-null    object
 18  bore               205 non-null    object
 19  stroke             205 non-null    object
 20  compression-ratio  205 non-null    float64
 21  horsepower         205 non-null    object
 22  peak-rpm           205 non-null    object
 23  city-mpg           205 non-null    int64
 24  highway-mpg        205 non-null    int64
 25  price              205 non-null    object
dtypes: float64(5), int64(5), object(16)
memory usage: 41.8+ KB
None

In [ ]:
df_final=df_final.sort_values(by="Tanggal")
df_final['Harga'] = df_final['Harga'].astype('int64', copy=False)
df_final['Tanggal'] = pd.to_datetime(df_final['Tanggal'], format='%d/%m/%Y')
df_copy=df.drop(df.columns[[0]], axis=1)
item = df_copy.columns
df_final = pd.DataFrame(columns=['Komoditas','Harga','Tanggal'])
for item in df_copy:
    komo=df[['Komoditas(Rp)', item]]
    komo.rename(columns={item:'Harga'}, inplace=True)
    komo['Tanggal']=item
    komo.rename(columns={'Komoditas(Rp)':'Komoditas'}, inplace=True)
    df_final=df_final.append(komo)
    
df = df.drop(['C', 'D'], axis=1)
melb_cheap     = melb_data[melb_data['Price']  <= melb_data['Price'].describe()['25%']]

# Data Cleaning

1. Wrong format data
2. Duplicate data
3. Null/NaN data
4. Outlier

### 1. Wrong format data

In [ ]:
# cek data typesnya, biasanya yg harusnya numeric tapi malah object yg salah
df.dtypes

# dicoba ganti format ke numeric, biar kelitan kalau ada ERROR. kalau bisa artinya ga ada ERROR. kalau ERROR dikasih tau sama pythonnya.
normalized_losses_numeric = pd.to_numeric(df['normalized-losses'])

# untuk melihat unique value nya ada berapa, apakah wajar
df['fuel-type'].unique()
df.nunique()

# kalau mau replace value dengan null/NaN
df['normalized-losses'].replace('?',np.NaN)

# kalau mau merubah value
df_final['Komoditas'] = df_final['Komoditas'].str.replace('kg','').str.replace('(','').str.replace(')','')
df_final['Komoditas'] = df_final['Komoditas'].str.strip()

https://docs.python.org/3/library/string.html

### 2. Duplicate Data

In [5]:
# ngecek ada atau engga
print(np.where(df.duplicated() == True))

# kalau ada, dicek di baris ke berapa
print(df.duplicated().iloc[516:536])

# dicek secara mendetail, duplicate valuenya gimana
df.iloc[494]

# dari valuenya, dicek samanya gimana (itu perlu dihapus atau engga)
np.where(df['Description'] == 'UNION JACK FLAG LUGGAGE TAG')

(array([], dtype=int64),)

### 3. Null/NaN Data

In [ ]:
# ngecek apakah ada null/NaN value
df.isnull().values.any()

# ngeliat semua null data dalam format boolean
df.isnull()

# ngeluat berapa jumlah record yg berniai true dari DataFrame diatas
df.isnull().sum()

# di ilangin baris datanya atau
df.dropna()

# diisi dengan mean/median/mode
df.describe()
df.fillna(df['description'].mean())

### 4. Outlier

In [ ]:
# Cara 1
#import scipy.stats
import scipy.stats as stats

#set the resource list and the condition for outlier
list_df = df['Apps']
z_scores = stats.zscore(list_df) 
abs_z_scores = np.abs(z_scores)
filtered_entries = (abs_z_scores > 3)

df_Apps = list_df[filtered_entries]
print(df_Apps)

# kalau mau dibuang outliernya
df = df[filtered_entries]

#Visualize
fig = plt.figure()
ax = plt.axes()

ax.bar(df['Unnamed: 0'], df['Apps'])

ax.set_title('Application to College 1995')
ax.set_xlabel('Name of College')
ax.set_ylabel('Sum of Applications')

plt.show()

# to see detailly
df.iloc[483]






# Cara 2
# tentukan batas_atas dan batas_bawah
Q1 = list_TotalCost.quantile(.25)
Q2 = list_TotalCost.quantile(.50)
Q3 = list_TotalCost.quantile(.75)

IQR = (Q3 - Q1) * 1.5
batas_bawah= Q1-IQR
batas_atas = Q3+IQR

# buat fungsi untuk outlier
def find_outlier(yourlist):
    outlier = []
    for i in range(len(yourlist)):
        if yourlist[i] > batas_atas:
            outlier.append(yourlist[i])
        if yourlist[i] < batas_bawah:
            outlier.append(yourlist[i])
        
    return outlier

# ambil data dan menjalankan fungsi
list_TotalCost = df['TotalCost']
find_outlier(list_TotalCost)

# cek secara mendetail data outlier nya
df[df['TotalCost']  >= batas_atas]
print(df['TotalCost'].iloc[9])

df[df['TotalCost']  >= batas_bawah]
print(df['TotalCost'].iloc[])

# untuk menghilangkan yg melewati batas_atas
df.shape()
df = df[df['TotalCost']  <= batas_atas]
df
df.shape()

# untuk menghilangkan yg melebihi batas bawah
df.shape()
df = df[df['TotalCost']  >= batas_bawah]
df
df.shape()